name: Wakatime Stats

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'  # Run only on sundays

jobs:
  update-readme-with-wakatime-stats:
    name: Update README with Wakatime stats
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update Wakatime stats
        uses: claserre9/wakatime-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          WAKATIME_USER_ID: ${{ secrets.WAKATIME_USER_ID }}
          GH_TOKEN: ${{ secrets.GH_WAKATIME_STATS }}
          TABLE_STYLE: 'default'
          MAX_LANGUAGES: '5'           
          WAKATIME_TIME_RANGE: 'all_time'  
