name: Wakatime Stats

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 */7 * *'  # Run at midnight every day

jobs:
  update-readme-with-wakatime-stats:
    name: Update README with Wakatime stats
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update Wakatime stats
        uses: claserre9/wakatime-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          WAKATIME_USER_ID: ${{ secrets.WAKATIME_USER_ID }}
          GH_TOKEN: ${{ secrets.GH_WAKATIME_STATS }}
          TABLE_STYLE: 'default'       # optional: default, box, box-double
          MAX_LANGUAGES: '5'           # optional
          WAKATIME_TIME_RANGE: 'all_time'  # optional
